# Generated by Django 4.2.3 on 2023-07-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_news_slug_en_news_slug_ru_news_slug_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug_uz',
        ),
    ]
