# Generated by Django 4.2.3 on 2023-07-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_remove_news_slug_en_remove_news_slug_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_uz',
        ),
    ]
